sudo mv ~/.config/hypr/hyprland.conf ~/.config/hypr/hyprland.save
sudo mv ~/Hyprtheme/hyprland.conf ~/.config/hypr/
sudo mv ~/.config/waybar/config.jsonc ~/.config/waybar/config.save
sudo mv ~/Hyprtheme/config ~/.config/waybar/
sudo mv ~/.config/waybar/style.css ~/.config/waybar/style.save
sudo mv ~/Hyprtheme/style.css ~/.config/waybar/
sudo mv ~/.config/kitty/kitty.conf ~/.config/kitty/kitty.save
sudo mv ~/Hyprtheme/kitty.conf ~/.config/kitty/
sudo mv ~/Hyprtheme/nord.conf ~/.config/kitty/
sudo mv ~/Hyprtheme/waybar.sh ~/
